trigger:
  - wsl-xyb-port-5.5.y

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-18.04
    steps:
      - checkout: self
        persistCredentials: true
      - script: |
          set -e
          sudo apt update
          sudo apt install -y g++ make flex bison libssl-dev libelf-dev bc
          make -j`nproc` KCONFIG_CONFIG=Microsoft/config-wsl
          cp arch/x86_64/boot/bzImage $(Build.ArtifactStagingDirectory)/kernel
      - task: GitHubRelease@0
        displayName: Delete old release
        inputs:
          gitHubConnection: xyb
          repositoryName: xieyubo/WSL2-Linux-Kernel
          action: delete
          tag: latest
        continueOnError: true
      - script: |
          git push origin :refs/tags/latest
      - task: GitHubRelease@0
        displayName: Create new release
        inputs:
          gitHubConnection: xyb
          repositoryName: xieyubo/WSL2-Linux-Kernel
          action: create
          target: $(Build.SourceVersion)
          tagSource: manual
          tag: latest
          assetUploadMode: delete
          isPreRelease: true
          addChangeLog: false
